apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /data
      name: storage
      readOnly: true
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: podpvc
