apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: qq3
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"